spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smbms?serverTimezone=GMT%2B8&characterEncoding=UTF-8
    username: root
    password: 5124260
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      encoding: utf-8
  servlet:
    multipart:
      max-file-size: 6MB
      max-request-size: 50MB
logging:
  level:
    com.example.dao: debug
mybatis:
  type-aliases-package: com.example.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8086

